# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
permalink: pretty
title: PARC AI Ethics Committee
description: This project contains documents and notes for the PARC Ethics Review Committee.
baseurl: "/ai-ethics" 
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json", "README.md",  "script/", "LICENSE.txt", "lib/", "bin/", "Rakefile"]

aux_links:
  "AI Ethics on GitHub":
    - "//github.com/PARC/ai-ethics"
theme: jekyll-theme-minimal
